spring.application.name=order-service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Downstream services
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8083}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8082}

# Resilience4j Retry
resilience4j.retry.instances.inventoryService.max-attempts=3
resilience4j.retry.instances.inventoryService.wait-duration=1s

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=10s