spring.application.name=order-service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Downstream services
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8083}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8082}


#spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
